# Generated by Django 4.1.2 on 2022-10-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_adminarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminarticle',
            old_name='body',
            new_name='text',
        ),
    ]
